### ISSUE TITLE
Problem with Django 1.8 migrations

### ISSUE THREAD

**Issue by arthanson** [charettes/django-polymodels#8]
I create a very simple models.py with polymodels (shown below).  Running a makemigrations (initial - first time run) with Django 1.8 results in no migration being generated.  

If you create a proxy model of MainModel then the proxy model will get generated in the migration but MainModel never gets an initial migration created.

Not sure if this is an issue with polymodels or django-migrations, but only happens with polymodels.

```python
# -------
from django.db import models
from polymodels.models import PolymorphicModel


class Base1(PolymorphicModel):
    base_name = models.CharField(max_length=60)


class MainModel(Base1):
    main_name = models.CharField(max_length=60)

**Comment by charettes** [comment]
Strange, I managed to reproduce. Will look into this.

**Comment by charettes** [comment]
Can you confirm that adding the following to your models work around the issue:

```python
class Meta:
    app_label = '<app_label>'
```

Where `<app label>` is the label of the application containing your models.

**Comment by charettes** [comment]
This is related to [Django #21794](https://code.djangoproject.com/ticket/21794).

I added a support for Django 1.7 at a time where abstract model were required to have an `app_label` to prevent a deprecation warning. The thing is this bound all subclasses to the `'polymodels'` app instead of the one they were defined in.

Since `'polymodels'` doesn't have any migration it must explicitly be specified to `makemigrations` if you want changes to be detected, hence the `'No changes detected'` message you're getting.

Fix and new release are coming.

**Comment by charettes** [comment]
@arthanson, I uploaded version 1.3.0 to Pypi which solves your issue.
